env:
  - VER=v1.10.2
script:
  - wget "https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-3.2.3-signed.msi?_ga=1.206481363.1984634701.1457430571"
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git config --global user.name "travis_auto"
    git config --global user.email "qinka@live.com"
    cd ~
    git clone https://qinka:$GITHUB_API_KEY@github.com/Qinka/GetBoot2Docker.git
    cd GetBoot2Docker
    export RELHELP=$(pwd)
    cd "$TRAVIS_BUILD_DIR"
    cp *.iso $RELHELP
    cd $RELHELP
    git add .
    git commit -am"$(date)"
    git push origin master
    cd ~
    sudo rm -rf $RELHELP
    cd "$TRAVIS_BUILD_DIR"
  fi
